In [71]:
import numpy as np
import pandas as pd

In [72]:
# As for the phase-1 our idea is to get the recoomendations on basic (embeddings retreival) no big model 
# clean the datasets (preprocessing and basic embediings retrievals)

In [73]:
df=pd.read_csv(r"C:\nihal\rough\Reccomender_system_rough\uncleaned_Dataset\netflix_dataset.csv")
df2=pd.read_csv(r"C:\nihal\rough\Reccomender_system_rough\uncleaned_Dataset\movies.csv")

In [74]:
df.shape

(7787, 12)

In [75]:
df2.shape

(1040, 18)

In [76]:
df.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...

In [77]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [78]:
df = df.rename(columns={
    'show_id': 'id',
    'listed_in': 'metadata',
    'type': 'domain'
})

In [79]:
df['source'] = 'netflix'

df['title'] = df['title'].fillna('')
df['director'] = df['director'].fillna('')
df['cast'] = df['cast'].fillna('')
df['country'] = df['country'].fillna('')
df['rating'] = df['rating'].fillna('')
df['duration'] = df['duration'].fillna('')
df['metadata'] = df['metadata'].fillna('')
df['description'] = df['description'].fillna('')
df['language'] = ''

In [80]:
df['id'].value_counts()

id
s7787    1
s1       1
s2       1
s3       1
s4       1
        ..
s16      1
s15      1
s14      1
s13      1
s12      1
Name: count, Length: 7787, dtype: int64

In [81]:
#As all the id are unique

In [82]:
df['metadata']=df['metadata'].fillna("")+" "+df['description'].fillna("")

In [83]:
df['id'] = 'netflix_' + df['id'].astype(str)

In [84]:
df.head(1)

,id,domain,title,director,cast,country,date_added,release_year,rating,duration,metadata,description,source,language
0,netflix_s1,TV Show,3%,,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,netflix,

In [85]:
df['domain'].value_counts()

domain
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [86]:
df['metadata'].value_counts()

metadata
Comedies, International Movies, Music & Musicals A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
Children & Family Movies, Comedies When Elastigirl gets recruited for a high-profile crime-fighting mission, Mr. Incredible takes on his toughest assignment ever: full-time parenting.                       2
Dramas, International Movies, Thrillers Secrets bubble to the surface after a sensual encounter and an unforeseen crime entangle two friends and a woman caught between them.                                 2
Kids' TV This educational series for tiny tots features a toe-tapping spin on nursery rhymes with upbeat tunes and a diverse set of easy-to-follow lessons.                                                   2
International Movies, Thrillers As a woman scours Hyderabad for her missing husband, she becomes entangled in a conspiracy that suggests there’s more to the mystery than meets the eye.                      2
                                                                                                                                                                                                             ..
Dramas, International Movies When Lebanon's Civil War deprives Zozo of his family, he's left with grief and little means as he escapes to Sweden in search of his grandparents.                               1
Dramas, International Movies, Music & Musicals A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past.                        1
Documentaries, International Movies, Music & Musicals In this documentary, South African rapper Nasty C hits the stage and streets of Tokyo, introducing himself to the city's sights, sounds and culture.    1
International TV Shows, Reality TV Dessert wizard Adriano Zumbo looks for the next “Willy Wonka” in this tense competition that finds skilled amateurs competing for a $100,000 prize.                        1
Horror Movies, International Movies, Thrillers An architect and his wife move into a castle that is slated to become a luxury hotel. But something inside is determined to stop the renovation.               1
Name: count, Length: 7771, dtype: int64

In [87]:
df['title'].value_counts()

title
ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS    1
3%                                         1
07:19                                      1
23:59                                      1
9                                          1
                                          ..
Oct-01                                     1
3022                                       1
2,215                                      1
1994                                       1
1983                                       1
Name: count, Length: 7787, dtype: int64

In [88]:
df['title'].duplicated().sum()

np.int64(0)

In [89]:
df['combined'] = (
    'Title: ' + df['title'].fillna('') +
    ' Domain: ' + df['domain'].fillna('') +
    ' Genres: ' + df['metadata'].fillna('') +
    ' Director: ' + df['director'].fillna('') +
    ' Cast: ' + df['cast'].fillna('') +
    ' Country: ' + df['country'].fillna('') +
    ' Release Year: ' + df['release_year'].fillna('').astype(str) +
    ' Rating: ' + df['rating'].fillna('') +
    ' Duration: ' + df['duration'].fillna('') +
    ' Description: ' + df['description'].fillna('')
)

In [90]:
df= df[
    [
        'id',
        'source',
        'title',
        'domain',
        'metadata',
        'description',
        'release_year',
        'duration',
        'rating',
        'language',
        'country',
        'combined'
    ]
]

In [91]:
# no duplicate title names

In [92]:
df2.head(1)

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False

In [93]:
df2.columns

Index(['movie_id', 'title', 'content_type', 'genre_primary', 'genre_secondary',
       'release_year', 'duration_minutes', 'rating', 'language',
       'country_of_origin', 'imdb_rating', 'production_budget',
       'box_office_revenue', 'number_of_seasons', 'number_of_episodes',
       'is_netflix_original', 'added_to_platform', 'content_warning'],
      dtype='object')

In [94]:
df2 = df2.rename(columns={
    'movie_id': 'id',
    'content_type': 'domain',
    'country_of_origin': 'country'
})

In [95]:
df2['source'] = 'movies'

In [96]:
text_cols = [
    'title',
    'domain',
    'genre_primary',
    'genre_secondary',
    'rating',
    'language',
    'country',
    'content_warning'
]

for col in text_cols:
    df2[col] = df2[col].fillna('').astype(str)

In [97]:
numeric_cols = [
    'release_year',
    'duration_minutes',
    'imdb_rating',
    'production_budget',
    'box_office_revenue',
    'number_of_seasons',
    'number_of_episodes'
]

for col in numeric_cols:
    df2[col] = df2[col].fillna(0)

In [98]:
df2 = df2.rename(columns={
    'duration_minutes': 'duration'
})

In [99]:
df2['id']

0       movie_0001
1       movie_0002
2       movie_0003
3       movie_0004
4       movie_0005
           ...
1035    movie_0140
1036    movie_0517
1037    movie_0696
1038    movie_0056
1039    movie_0652
Name: id, Length: 1040, dtype: object

In [100]:
df2['domain'] = df2['domain'].replace({
    'TV Show': 'TV Series',
    'TV': 'TV Series',
    'Movie': 'Movie',
    'Documentary': 'Documentary'
})

In [101]:
df2['description'] = ''

In [102]:
df2.head()

,id,title,domain,genre_primary,genre_secondary,release_year,duration,rating,language,country,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning,source,description
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,0.0,0.0,0.0,0.0,0.0,False,2023-08-07,False,movies,
1,movie_0002,Storm Warrior,Stand-up Comedy,Sci-Fi,,2017,37.0,PG,Japanese,USA,3.3,0.0,0.0,0.0,0.0,False,2022-01-28,True,movies,
2,movie_0003,Fire Family,Movie,Drama,,2003,142.0,TV-MA,English,USA,8.5,2114120.0,0.0,0.0,0.0,False,2021-05-04,True,movies,
3,movie_0004,Our Princess,Documentary,Sci-Fi,,2011,131.0,NC-17,Japanese,USA,5.3,0.0,0.0,0.0,0.0,False,2022-11-26,False,movies,
4,movie_0005,Warrior Mission,Documentary,Sport,Mystery,2015,91.0,TV-G,English,USA,3.1,0.0,0.0,0.0,0.0,False,2023-06-15,False,movies,

In [103]:
df2['metadata'] = (
    df2['genre_primary'].fillna('') + ' ' +
    df2['genre_secondary'].fillna('')
)

In [104]:
df2.head(1)

,id,title,domain,genre_primary,genre_secondary,release_year,duration,rating,language,country,...,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning,source,description,metadata
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,...,0.0,0.0,0.0,0.0,False,2023-08-07,False,movies,,History Thriller

In [105]:
df2.dtypes

id                      object
title                   object
domain                  object
genre_primary           object
genre_secondary         object
release_year             int64
duration               float64
rating                  object
language                object
country                 object
imdb_rating            float64
production_budget      float64
box_office_revenue     float64
number_of_seasons      float64
number_of_episodes     float64
is_netflix_original       bool
added_to_platform       object
content_warning         object
source                  object
description             object
metadata                object
dtype: object

In [106]:
df2['combined'] = (
    'Title: ' + df2['title'].fillna('') +
    ' Domain: ' + df2['domain'].fillna('') +
    ' Genres: ' + df2['metadata'].fillna('') +
    ' Release Year: ' + df2['release_year'].fillna('').astype(str) +
    ' Duration: ' + df2['duration'].fillna('').astype(str) +
    ' Rating: ' + df2['rating'].fillna('') +
    ' Language: ' + df2['language'].fillna('') +
    ' Country: ' + df2['country'].fillna('') +
    ' IMDb Rating: ' + df2['imdb_rating'].fillna('').astype(str) +
    ' Content Warning: ' + df2['content_warning'].astype(str).fillna('')
)

In [107]:
df.head()

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,combined
0,netflix_s1,netflix,3%,TV Show,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020,4 Seasons,TV-MA,,Brazil,Title: 3% Domain: TV Show Genres: Internationa...
1,netflix_s2,netflix,07:19,Movie,"Dramas, International Movies After a devastati...",After a devastating earthquake hits Mexico Cit...,2016,93 min,TV-MA,,Mexico,"Title: 07:19 Domain: Movie Genres: Dramas, Int..."
2,netflix_s3,netflix,23:59,Movie,"Horror Movies, International Movies When an ar...","When an army recruit is found dead, his fellow...",2011,78 min,R,,Singapore,Title: 23:59 Domain: Movie Genres: Horror Movi...
3,netflix_s4,netflix,9,Movie,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2009,80 min,PG-13,,United States,Title: 9 Domain: Movie Genres: Action & Advent...
4,netflix_s5,netflix,21,Movie,Dramas A brilliant group of students become ca...,A brilliant group of students become card-coun...,2008,123 min,PG-13,,United States,Title: 21 Domain: Movie Genres: Dramas A brill...

In [108]:
df.columns

Index(['id', 'source', 'title', 'domain', 'metadata', 'description',
       'release_year', 'duration', 'rating', 'language', 'country',
       'combined'],
      dtype='object')

In [109]:
df2.columns

Index(['id', 'title', 'domain', 'genre_primary', 'genre_secondary',
       'release_year', 'duration', 'rating', 'language', 'country',
       'imdb_rating', 'production_budget', 'box_office_revenue',
       'number_of_seasons', 'number_of_episodes', 'is_netflix_original',
       'added_to_platform', 'content_warning', 'source', 'description',
       'metadata', 'combined'],
      dtype='object')

In [110]:
df2= df2[
    [
        'id',
        'source',
        'title',
        'domain',
        'metadata',
        'description',
        'release_year',
        'duration',
        'rating',
        'language',
        'country',
        'imdb_rating',
        'production_budget',
        'box_office_revenue',
        'number_of_seasons',
        'number_of_episodes',
        'is_netflix_original',
        'added_to_platform',
        'content_warning',
        'combined'
    ]
]

In [111]:
df.shape

(7787, 12)

In [112]:
df2.shape

(1040, 20)

In [113]:
df2["title"] = df2["title"].str.strip().str.lower()
df2['title'].duplicated().sum()

np.int64(367)

In [114]:
df2.groupby("title").filter(lambda x: len(x) > 1)

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning,combined
1,movie_0002,movies,storm warrior,Stand-up Comedy,Sci-Fi,,2017,37.0,PG,Japanese,USA,3.3,0.0,0.0,0.0,0.0,False,2022-01-28,True,Title: Storm Warrior Domain: Stand-up Comedy G...
3,movie_0004,movies,our princess,Documentary,Sci-Fi,,2011,131.0,NC-17,Japanese,USA,5.3,0.0,0.0,0.0,0.0,False,2022-11-26,False,Title: Our Princess Domain: Documentary Genres...
7,movie_0008,movies,old house,Movie,Horror,,1991,109.0,TV-Y,Spanish,South Korea,7.7,629216.0,3995303.0,0.0,0.0,False,2020-10-04,False,Title: Old House Domain: Movie Genres: Horror ...
11,movie_0012,movies,bright war,Movie,Crime Sci-Fi,,1997,95.0,G,English,South Korea,9.9,0.0,72997481.0,0.0,0.0,False,2025-05-22,False,Title: Bright War Domain: Movie Genres: Crime ...
13,movie_0014,movies,little war,Movie,Mystery,,1990,117.0,TV-14,Korean,Japan,8.4,0.0,32793336.0,0.0,0.0,True,2020-10-01,False,Title: Little War Domain: Movie Genres: Myster...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,movie_0140,movies,city empire,Documentary,Sport,,2023,19.0,TV-14,English,France,5.6,0.0,0.0,0.0,0.0,False,2025-06-20,False,Title: City Empire Domain: Documentary Genres:...
1036,movie_0517,movies,storm legend,TV Series,War,,1998,48.0,TV-MA,English,Japan,6.0,0.0,0.0,9.0,85.0,False,2021-07-21,False,Title: Storm Legend Domain: TV Series Genres: ...
1037,movie_0696,movies,house empire,Limited Series,Biography,,2010,54.0,G,Korean,USA,7.2,0.0,0.0,10.0,174.0,False,2023-08-19,False,Title: House Empire Domain: Limited Series Gen...
1038,movie_0056,movies,big princess,Movie,Adventure Comedy,,1997,137.0,TV-Y,English,USA,6.2,3593765.0,2259750.0,0.0,0.0,True,2021-01-18,False,Title: Big Princess Domain: Movie Genres: Adve...
1039,movie_0652,movies,our night,Movie,History,,2015,102.0,TV-MA,English,USA,10.0,14939487.0,21771252.0,0.0,0.0,False,2024-10-15,True,Title: Our Night Domain: Movie Genres: History...

In [115]:
df2[df2['title']=='old house']

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning,combined
7,movie_0008,movies,old house,Movie,Horror,,1991,109.0,TV-Y,Spanish,South Korea,7.7,629216.0,3995303.0,0.0,0.0,False,2020-10-04,False,Title: Old House Domain: Movie Genres: Horror ...
185,movie_0186,movies,old house,TV Series,Comedy,,1999,70.0,TV-G,English,USA,0.0,0.0,0.0,9.0,151.0,False,2024-03-08,True,Title: Old House Domain: TV Series Genres: Com...
463,movie_0464,movies,old house,Limited Series,Sport,,1993,38.0,TV-Y,English,USA,4.9,0.0,0.0,6.0,176.0,False,2021-05-04,True,Title: Old House Domain: Limited Series Genres...
937,movie_0938,movies,old house,Movie,Crime War,,1995,116.0,R,English,USA,1.7,6877911.0,65073829.0,0.0,0.0,True,2021-04-05,True,Title: Old House Domain: Movie Genres: Crime W...

In [116]:
# as  here old house title has for 4 different domain and metadat so we couldn't convert them directly as all of them are not 
# belong to one type of domain so that makes all of them are unique with respect to content ,as if you give same movie_id for all of them then there will be error
# in the retreival in user watch history as movie_id is primary key we need to match them.

In [117]:
df[df["title"].isin(df2["title"])]

Empty DataFrame
Columns: [id, source, title, domain, metadata, description, release_year, duration, rating, language, country, combined]
Index: []

In [118]:
df2["title"] = df2["title"].str.strip().str.lower()
df2["domain"] = df2["domain"].fillna('').str.strip()
df2["metadata"] = df2["metadata"].fillna('').str.strip()

In [119]:
df2['title'].duplicated().sum()

np.int64(367)

In [120]:
COMMON_COLUMNS = [
    'id',
    'source',
    'title',
    'domain',
    'metadata',
    'description',
    'release_year',
    'duration',
    'rating',
    'language',
    'country',
    'combined'
]

In [121]:
## This snippet is valid for if for same movie_title and content it had mistakenly given different movie_id we will handel by 
## same tiltle we will give first movie_id for all of them then there will be error when joining with user_watch histroy as tehre only 
## movie_id will be matching with them 

# # 1. Normalize titles (VERY IMPORTANT)
# df["title"] = df["title"].str.strip().str.lower()
# df2["title"] = df2["title"].str.strip().str.lower()

# # 2. Merge (df2 is PRIMARY)
# merged = pd.merge(df2, df, on="title", how="left", suffixes=("_df2", "_df1"))
# print(merged.head(1))
# merged["metadata"] = (
#     merged["metadata_df2"].fillna('') + " " +
#     merged["metadata_df1"].fillna('')
# ).str.strip()
# merged = merged.drop(columns=["metadata_df2", "metadata_df1"])
# merged["domain"] = (
#     merged["domain_df2"].fillna('') + " " +
#     merged["domain_df1"].fillna('')
# ).str.strip()
# merged = merged.drop(columns=["domain_df2", "domain_df1"])
# merged = merged.drop(columns=["movie_id_df1"])

# merged = merged.rename(columns={"movie_id_df2": "movie_id"})
# # find titles in df that are NOT in df2
# unmatched_df = df[~df["title"].isin(df2["title"])].copy()

# # rename id column to match schema
# unmatched_df = unmatched_df.rename(columns={"id": "id"})

# # add missing columns to match structure
# unmatched_df["movie_id"] = unmatched_df["movie_id"]  # optional placeholder
# merged = merged.reset_index(drop=True)
# unmatched_df = unmatched_df.reset_index(drop=True)
# # unmatched_df = unmatched_df.reindex(columns=merged.columns)

In [122]:
df=df[COMMON_COLUMNS]
df2=df2[COMMON_COLUMNS]

In [123]:
final_df = pd.concat([df, df2], ignore_index=True)

In [124]:
final_df.shape

(8827, 12)

In [125]:
final_df['title'].duplicated().sum()

np.int64(367)

In [126]:
final_df.sample(5)

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,combined
3626,netflix_s3627,netflix,Life Ki Toh Lag Gayi,Movie,"Action & Adventure, Comedies, Dramas A vengefu...","A vengeful son, a cop on a mission, a wannabe ...",2012,109 min,TV-MA,,India,Title: Life Ki Toh Lag Gayi Domain: Movie Genr...
4777,netflix_s4778,netflix,Paris Is Us,Movie,"Dramas, Independent Movies, International Movi...",Amid a turbulent romance and rising tensions i...,2019,84 min,TV-MA,,France,Title: Paris Is Us Domain: Movie Genres: Drama...
8649,movie_0863,movies,fire house,Movie,Music Mystery,,2003,139.0,TV-14,French,USA,Title: Fire House Domain: Movie Genres: Music ...
5331,netflix_s5332,netflix,Sacred Games,TV Show,"Crime TV Shows, International TV Shows, TV Dra...",A link in their pasts leads an honest cop to a...,2019,2 Seasons,TV-MA,,"India, United States",Title: Sacred Games Domain: TV Show Genres: Cr...
6959,netflix_s6960,netflix,The Unborn Child,Movie,"Horror Movies, International Movies A couple a...",A couple and their young daughter are haunted ...,2011,93 min,TV-MA,,Thailand,Title: The Unborn Child Domain: Movie Genres: ...

In [127]:
print("Netflix:", df['domain'].unique())
print("Movies:", df2['domain'].unique())

Netflix: ['TV Show' 'Movie']
Movies: ['Stand-up Comedy' 'Movie' 'Documentary' 'TV Series' 'Limited Series']

In [128]:
df['domain'] = df['domain'].replace({
    'TV Show': 'TV Series',
    'Movie': 'Movie'
})

In [129]:
print(
    df2[df2['domain'] == 'Stand-up Comedy']
    [['title', 'domain', 'metadata']]
    .head(20)
)

              title           domain             metadata
0     dragon legend  Stand-up Comedy     History Thriller
1     storm warrior  Stand-up Comedy               Sci-Fi
16   kingdom battle  Stand-up Comedy                  War
26      house house  Stand-up Comedy              Western
27      legend hero  Stand-up Comedy    Biography Romance
43      dragon city  Stand-up Comedy      War Documentary
57      day mystery  Stand-up Comedy                Drama
84   mission secret  Stand-up Comedy          Crime Crime
93        dark city  Stand-up Comedy      Western Western
97            a war  Stand-up Comedy            Adventure
102   family battle  Stand-up Comedy        Sci-Fi Action
128    mission fire  Stand-up Comedy         Sci-Fi Crime
133     story night  Stand-up Comedy  Adventure Animation
172   little dragon  Stand-up Comedy       Sci-Fi History
190     war kingdom  Stand-up Comedy            Adventure
201     city empire  Stand-up Comedy     Horror Adventure
211      story king  Stand-up Comedy                  War
213     last dragon  Stand-up Comedy     Animation Comedy
225         a dream  Stand-up Comedy              Western
226      last storm  Stand-up Comedy               Family

In [130]:
df2['domain'] = df2['domain'].replace({
    'Movie': 'Movie',
    'TV Series': 'TV Series',
    'Limited Series': 'TV Series',
    'Documentary': 'Documentary'
})

In [131]:
print("Total items:", len(final_df))
print("Unique IDs:", final_df['id'].nunique())

Total items: 8827
Unique IDs: 8787

In [132]:
dup_ids = final_df[final_df['id'].duplicated(keep=False)].sort_values('id')

dup_ids[['id', 'source', 'title', 'domain', 'metadata']]

              id  source            title       domain             metadata
7820  movie_0034  movies  mission kingdom    TV Series           War Horror
8800  movie_0034  movies  mission kingdom    TV Series           War Horror
7821  movie_0035  movies    princess love    TV Series       Family Romance
8821  movie_0035  movies    princess love    TV Series       Family Romance
7829  movie_0043  movies       city queen  Documentary               Family
...          ...     ...              ...          ...                  ...
8808  movie_0964  movies   journey empire    TV Series    Crime Documentary
8766  movie_0980  movies       war battle    TV Series  Adventure Biography
8807  movie_0980  movies       war battle    TV Series  Adventure Biography
8790  movie_0996  movies   secret mission    TV Series               Sci-Fi
8782  movie_0996  movies   secret mission    TV Series               Sci-Fi

[80 rows x 5 columns]

In [133]:
final_df.drop_duplicates(inplace=True)

In [134]:
items = pd.concat(
    [final_df],
    ignore_index=True
)

In [135]:
print("Total items:", len(items))
print("Unique IDs:", items['id'].nunique())

Total items: 8787
Unique IDs: 8787

In [136]:
print(items['id'].isna().sum())

0

In [137]:
print(items.groupby('source')['domain'].unique())

source
movies     [Stand-up Comedy, Movie, Documentary, TV Serie...
netflix                                     [TV Show, Movie]
Name: domain, dtype: object

In [138]:
items[items['domain']=='Data Science']

Empty DataFrame
Columns: [id, source, title, domain, metadata, description, release_year, duration, rating, language, country, combined]
Index: []

In [139]:
items.tail(5)

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,combined
8782,movie_0996,movies,secret mission,TV Series,Sci-Fi,,1997,69.0,NC-17,English,South Korea,Title: Secret Mission Domain: TV Series Genres...
8783,movie_0997,movies,house empire,TV Series,History Biography,,2024,21.0,R,French,USA,Title: House Empire Domain: TV Series Genres: ...
8784,movie_0998,movies,day legend,Limited Series,Fantasy,,2013,69.0,TV-14,English,USA,Title: Day Legend Domain: Limited Series Genre...
8785,movie_0999,movies,ice war,Movie,Crime,,1997,16.0,TV-Y7,English,USA,Title: Ice War Domain: Movie Genres: Crime Re...
8786,movie_1000,movies,last night,TV Series,Sport,,1993,42.0,NC-17,English,UK,Title: Last Night Domain: TV Series Genres: Sp...

In [140]:
items[items['title']=='Certified Scrum Master']

Empty DataFrame
Columns: [id, source, title, domain, metadata, description, release_year, duration, rating, language, country, combined]
Index: []

In [141]:
!pip install langid

Requirement already satisfied: langid in c:\users\nihal\torch_venv\lib\site-packages (1.1.6)
Requirement already satisfied: numpy in c:\users\nihal\torch_venv\lib\site-packages (from langid) (2.2.6)

In [142]:
!pip install deep_translator

Requirement already satisfied: deep_translator in c:\users\nihal\torch_venv\lib\site-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\nihal\torch_venv\lib\site-packages (from deep_translator) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\nihal\torch_venv\lib\site-packages (from deep_translator) (2.33.1)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\nihal\torch_venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\nihal\torch_venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nihal\torch_venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nihal\torch_venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\nihal\torch_venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\nihal\torch_venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2026.4.22)

In [143]:
## As by seeing data in datset we can observe data is from other than english so we should refine into english

import langid
from deep_translator import GoogleTranslator

def convert_to_english(text):
    try:
        lang, _ = langid.classify(text)
        if lang != 'en':
            return GoogleTranslator(source=lang, target='en').translate(text)
        return text
    except:
        return text

In [144]:
translate_cols = [
    'title',
    'domain',
    'metadata',
    'description',
    'language',
    'country'
]

for col in translate_cols:
    items[col] = items[col].fillna('').astype(str)
    items[col] = items[col].apply(convert_to_english)
items['combined'] = (
    items['title'] + ' ' +
    items['domain'] + ' ' +
    items['metadata'] + ' ' +
    items['description']
)

## As perform basic preprocessing such as 
Removing i)HTML tags
ii)URLS
iii)Punctutations
iv) stopwords
v) making some of the complex english word convertion into full form.

In [145]:
import re

def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)


def remove_urls(text):
    return re.sub(
        r'https?://\S+|www\.\S+',
        '',
        text
    )


def preprocess(text):
    text = str(text).lower().strip()
    text = remove_html_tags(text)
    text = remove_urls(text)
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [146]:
for col in translate_cols:
    items[col] = items[col].apply(preprocess)
items['combined'] = (
    "Title: " + items['title'] + " "
    + "Domain: " + items['domain'] + " "
    + "Metadata: " + items['metadata'] + " "
    + "Description: " + items['description']
)

In [147]:
items.head()

,id,source,title,domain,metadata,description,release_year,duration,rating,language,country,combined
0,netflix_s1,netflix,3%,tv show,"international tv shows, tv dramas, tv sci-fi &...",in a future where the elite inhabit an island ...,2020,4 Seasons,TV-MA,,brazil,Title: 3% Domain: tv show Metadata: internatio...
1,netflix_s2,netflix,07:19,movie,"dramas, international movies after a devastati...",after a devastating earthquake hits mexico cit...,2016,93 min,TV-MA,,mexico,"Title: 07:19 Domain: movie Metadata: dramas, i..."
2,netflix_s3,netflix,23:59,movie,"horror movies, international movies when an ar...","when an army recruit is found dead, his fellow...",2011,78 min,R,,singapore,Title: 23:59 Domain: movie Metadata: horror mo...
3,netflix_s4,netflix,9,movie,"action & adventure, independent movies, sci-fi...","in a postapocalyptic world, rag-doll robots hi...",2009,80 min,PG-13,,united states,Title: 9 Domain: movie Metadata: action & adve...
4,netflix_s5,netflix,21,movie,dramas a brilliant group of students become ca...,a brilliant group of students become card-coun...,2008,123 min,PG-13,,united states,Title: 21 Domain: movie Metadata: dramas a bri...

In [149]:
from sentence_transformers import SentenceTransformer

# Load SBERT model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Text to embed
corpus = items['combined'].tolist()

# Generate normalized embeddings
arr = model.encode(
    corpus,
    convert_to_tensor=True,
    normalize_embeddings=True
)

print("Embedding shape:", arr.shape)

c:\Users\nihal\torch_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5042.82it/s]

Embedding shape: torch.Size([8787, 384])

In [150]:
import os
import torch

folder_path = r"C:\nihal\rough\Reccomender_system_rough\Cleaned_dataset"

torch.save(
    arr,
    os.path.join(folder_path, "item_embeddings.pt")
)

In [151]:
items.to_csv(
    os.path.join(folder_path, "items.csv"),
    index=False
)

In [152]:
# Test queries
query1 = "Blood & Water"
query2 = "deep learning"
query3 = "romantic movie"
query4 = "crime thriller"
query5 = "guitar music"
query6 = "history of kings"
query7 = "world war history military strategy"

query_embedding = model.encode(
    query1,
    convert_to_tensor=True,
    normalize_embeddings=True
)

print(query_embedding.shape)

torch.Size([384])

In [153]:
from sentence_transformers.util import cos_sim

scores = cos_sim(query_embedding, arr)[0]

top_k = 5
top_results = scores.topk(k=top_k)

In [154]:
for score, idx in zip(
    top_results.values,
    top_results.indices
):
    row = items.iloc[idx.item()]

    print(
        f"Title: {row['title']}"
    )
    print(
        f"Domain: {row['domain']}"
    )
    print(
        f"Metadata: {row['metadata']}"
    )
    print(
        f"Score: {score.item():.4f}"
    )
    print("-" * 50)

Title: blood & water
Domain: tv show
Metadata: international tv shows, tv dramas, tv mysteries after crossing paths at a party, a cape town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.
Score: 0.4495
--------------------------------------------------
Title: blood will tell
Domain: movie
Metadata: dramas, independent movies, international movies family patriarch elías begins to unravel after the death of his wife – which casts a suspicious light on her tragic accident.
Score: 0.3865
--------------------------------------------------
Title: fire in the blood
Domain: movie
Metadata: documentaries, international movies dylan mohan gray examines africa's aids crisis and activists' battle with pharmaceutical companies to make life-saving hiv drugs more affordable.
Score: 0.3678
--------------------------------------------------
Title: the future of water
Domain: tv show
Metadata: docuseries, international tv shows, science & nature tv a look at the deeply intertwined history of humanity and fresh water reveals looming challenges that could upend power structures around the world.
Score: 0.3641
--------------------------------------------------
Title: suburra: blood on rome
Domain: tv show
Metadata: crime tv shows, international tv shows, tv dramas in 2008, a fight over land in a seaside town near rome spirals into a deadly battle between organized crime, corrupt politicians and the vatican.
Score: 0.3609
--------------------------------------------------

query_embedding
      │
      │ cosine similarity
      ↓
arr
(all item embeddings)
      │
      ↓
scores
(one score for every item)
      │
      ↓
topk(5)
      │
      ↓
5 most semantically similar items

In [155]:
results = []

for score, idx in zip(
    top_results.values,
    top_results.indices
):
    row_data = {
        'title': items['title'].iloc[idx.item()],
        'domain': items['domain'].iloc[idx.item()],
        'metadata': items['metadata'].iloc[idx.item()],
        'score': score.item()
    }

    results.append(row_data)

fin = pd.DataFrame(results)

print(fin)

                    title   domain  \
0           blood & water  tv show
1         blood will tell    movie
2       fire in the blood    movie
3     the future of water  tv show
4  suburra: blood on rome  tv show

                                            metadata     score
0  international tv shows, tv dramas, tv mysterie...  0.449456
1  dramas, independent movies, international movi...  0.386489
2  documentaries, international movies dylan moha...  0.367761
3  docuseries, international tv shows, science & ...  0.364103
4  crime tv shows, international tv shows, tv dra...  0.360895

In [156]:
movie_history = pd.read_csv(
    r"C:\nihal\rough\Reccomender_system_rough\uncleaned_Dataset\watch_history.csv"
)

In [157]:
print(movie_history.shape)
print(movie_history.columns)
movie_history.head()

(105000, 12)
Index(['session_id', 'user_id', 'movie_id', 'watch_date', 'device_type',
       'watch_duration_minutes', 'progress_percentage', 'action', 'quality',
       'location_country', 'is_download', 'user_rating'],
      dtype='object')

,session_id,user_id,movie_id,watch_date,device_type,watch_duration_minutes,progress_percentage,action,quality,location_country,is_download,user_rating
0,session_000001,user_07271,movie_0511,2025-11-13,Tablet,63.9,34.6,completed,HD,USA,False,NaN
1,session_000002,user_00861,movie_0588,2025-02-26,Laptop,120.1,44.2,started,HD,USA,False,NaN
2,session_000003,user_05391,movie_0694,2024-12-15,Desktop,572.1,84.7,started,HD,Canada,False,1.0
3,session_000004,user_05192,movie_0234,2024-09-30,Desktop,395.3,89.9,completed,SD,USA,False,5.0
4,session_000005,user_05735,movie_0390,2024-08-04,Tablet,14.6,6.2,completed,HD,USA,False,NaN

In [158]:
movie_history = movie_history.rename(columns={
    'session_id': 'session_id',
    'user_id': 'user_id',
    'movie_id': 'item_id',
    'watch_date': 'interaction_date',
    'watch_duration_minutes': 'time'
})

In [159]:
movie_history['interaction_date'] = pd.to_datetime(
    movie_history['interaction_date'],
    errors='coerce'
)

In [160]:
print(movie_history['interaction_date'].isna().sum())

0

In [161]:
movie_history['time'] = pd.to_numeric(
    movie_history['time'],
    errors='coerce'
)

movie_history['progress_percentage'] = pd.to_numeric(
    movie_history['progress_percentage'],
    errors='coerce'
)

movie_history['user_rating'] = pd.to_numeric(
    movie_history['user_rating'],
    errors='coerce'
)

In [162]:
movie_history.head(1)

,session_id,user_id,item_id,interaction_date,device_type,time,progress_percentage,action,quality,location_country,is_download,user_rating
0,session_000001,user_07271,movie_0511,2025-11-13,Tablet,63.9,34.6,completed,HD,USA,False,NaN

In [163]:
print(movie_history.isna().sum())

session_id                 0
user_id                    0
item_id                    0
interaction_date           0
device_type                0
time                   12332
progress_percentage     8514
action                     0
quality                    0
location_country           0
is_download                0
user_rating            83903
dtype: int64

In [164]:
print("Users:", movie_history['user_id'].nunique())
print("Movies:", movie_history['item_id'].nunique())
print("Rows:", len(movie_history))

Users: 10000
Movies: 1000
Rows: 105000

In [165]:
print(movie_history['user_id'].isna().sum())
print(movie_history['item_id'].isna().sum())

0
0

In [166]:
movie_history = movie_history.dropna(
    subset=['user_id', 'item_id']
).copy()

In [167]:
valid_movie_ids = set(
    items.loc[
        items['source'].str.lower().eq('movies'),
        'id'
    ]
)

print(
    "Movie history IDs:",
    movie_history['item_id'].nunique()
)

print(
    "Matched IDs:",
    movie_history['item_id'].isin(valid_movie_ids).sum()
)

print(
    "Unmatched IDs:",
    (~movie_history['item_id'].isin(valid_movie_ids)).sum()
)

Movie history IDs: 1000
Matched IDs: 105000
Unmatched IDs: 0

In [168]:
print(movie_history['action'].value_counts())
print(movie_history['progress_percentage'].describe())
print(movie_history['time'].describe())
print(movie_history['user_rating'].describe())

action
started      26488
stopped      26266
paused       26217
completed    26029
Name: count, dtype: int64
count    96486.000000
mean        49.970533
std         28.821700
min          0.000000
25%         25.100000
50%         49.800000
75%         74.900000
max        100.000000
Name: progress_percentage, dtype: float64
count    92668.000000
mean        65.692239
std         68.376775
min          0.200000
25%         29.100000
50%         51.200000
75%         82.400000
max        799.300000
Name: time, dtype: float64
count    21097.000000
mean         3.356354
std          1.243011
min          1.000000
25%          2.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: user_rating, dtype: float64

In [169]:
print(movie_history['action'].value_counts())
print(movie_history['progress_percentage'].describe())
print(movie_history['time'].describe())
print(movie_history['user_rating'].describe())

action
started      26488
stopped      26266
paused       26217
completed    26029
Name: count, dtype: int64
count    96486.000000
mean        49.970533
std         28.821700
min          0.000000
25%         25.100000
50%         49.800000
75%         74.900000
max        100.000000
Name: progress_percentage, dtype: float64
count    92668.000000
mean        65.692239
std         68.376775
min          0.200000
25%         29.100000
50%         51.200000
75%         82.400000
max        799.300000
Name: time, dtype: float64
count    21097.000000
mean         3.356354
std          1.243011
min          1.000000
25%          2.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: user_rating, dtype: float64

In [170]:
time_cap = movie_history['time'].quantile(0.99)

movie_history['time_capped'] = (
    movie_history['time']
    .clip(upper=time_cap)
)

In [171]:
movie_history['time_norm'] = (
    movie_history['time_capped'] /
    movie_history['time_capped'].max()
)

In [172]:
movie_history['time_norm'] = (
    movie_history['time_norm'].fillna(0)
)

In [173]:
movie_history['progress_norm'] = (
    movie_history['progress_percentage']
    .fillna(0) / 100
)

Convert action into a numerical signal

In [174]:
action_weight = {
    'started': 0.25,
    'paused': 0.50,
    'stopped': 0.60,
    'completed': 1.00
}

In [175]:
movie_history['action_score'] = (
    movie_history['action']
    .map(action_weight)
    .fillna(0)
)

In [176]:
movie_history['rating_score'] = (
    movie_history['user_rating'] / 5
)

In [177]:
movie_history['engagement_score'] = (
    0.35 * movie_history['progress_norm'] +
    0.25 * movie_history['time_norm'] +
    0.25 * movie_history['action_score'] +
    0.15 * movie_history['rating_score'].fillna(
        movie_history['progress_norm']
    )
)

In [178]:
print(
    movie_history[
        [
            'action',
            'progress_percentage',
            'time',
            'user_rating',
            'engagement_score'
        ]
    ].head(20)
)

       action  progress_percentage   time  user_rating  engagement_score
0   completed                 34.6   63.9          NaN          0.466944
1     started                 44.2  120.1          NaN          0.366093
2     started                 84.7  572.1          1.0          0.638950
3   completed                 89.9  395.3          5.0          0.964650
4   completed                  6.2   14.6          NaN          0.291040
5   completed                 63.7   43.4          NaN          0.598346
6     stopped                 63.1  165.9          NaN          0.579590
7      paused                 57.4  100.4          NaN          0.481045
8      paused                  9.8   29.0          NaN          0.193943
9     stopped                 74.1   32.5          NaN          0.542850
10    started                 62.1    NaN          NaN          0.373000
11    started                 69.7   34.7          NaN          0.434863
12    stopped                  NaN    3.7          NaN          0.152545
13    started                 71.6   30.7          NaN          0.441612
14     paused                 30.7   59.9          5.0          0.423643
15    started                 65.2   31.0          NaN          0.409819
16    started                 37.9   39.3          NaN          0.279027
17    started                 92.0    NaN          3.0          0.474500
18     paused                 72.3   32.7          NaN          0.508988
19     paused                  5.5   53.0          NaN          0.188948

In [179]:
movie_interactions = (
    movie_history
    .groupby(
        ['user_id', 'item_id'],
        as_index=False
    )
    .agg(
        interaction_date=('interaction_date', 'max'),
        engagement_score=('engagement_score', 'max')
    )
)

In [180]:
print(
    movie_interactions
    .groupby('user_id')
    .size()
    .describe()
)

count    10000.000000
mean         9.947000
std          3.134928
min          2.000000
25%          8.000000
50%         10.000000
75%         12.000000
max         22.000000
dtype: float64

In [181]:
movie_interactions = movie_interactions.sort_values(
    ['user_id', 'interaction_date']
).reset_index(drop=True)

In [182]:
train_list = []
test_list = []

for user_id, group in movie_interactions.groupby('user_id'):

    group = group.sort_values('interaction_date')

    # Keep previous interactions as a DataFrame
    train_list.append(group.iloc[:-1])

    # Keep last interaction as a one-row DataFrame
    test_list.append(group.iloc[[-1]])

# Combine DataFrames
train_interactions = pd.concat(
    train_list,
    ignore_index=True
)

test_interactions = pd.concat(
    test_list,
    ignore_index=True
)

In [183]:
print("Train shape:", train_interactions.shape)
print("Test shape:", test_interactions.shape)

print("Train users:", train_interactions['user_id'].nunique())
print("Test users:", test_interactions['user_id'].nunique())

Train shape: (89470, 4)
Test shape: (10000, 4)
Train users: 10000
Test users: 10000

In [184]:
assert len(items) == arr.shape[0]

assert items['id'].is_unique

print("Item/embedding alignment verified.")
print("Items:", len(items))
print("Embedding rows:", arr.shape[0])

Item/embedding alignment verified.
Items: 8787
Embedding rows: 8787

In [185]:
movie_info = items[
    [
        'id',
        'title',
        'combined',
        'metadata',
        'domain'
    ]
].copy()

movie_history = movie_history.merge(
    movie_info,
    left_on='item_id',
    right_on='id',
    how='left'
)

movie_history = movie_history.drop(
    columns=['id']
)

In [186]:
movie_history.columns

Index(['session_id', 'user_id', 'item_id', 'interaction_date', 'device_type',
       'time', 'progress_percentage', 'action', 'quality', 'location_country',
       'is_download', 'user_rating', 'time_capped', 'time_norm',
       'progress_norm', 'action_score', 'rating_score', 'engagement_score',
       'title', 'combined', 'metadata', 'domain'],
      dtype='object')

In [197]:
import os

# Define the folder path
folder_path = r"C:\nihal\rough\Reccomender_system_rough\Cleaned_Dataset"

# Create folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

In [198]:
# explicit index mapping

In [199]:
# Save complete movie interactions
movie_history.to_csv(
    os.path.join(folder_path, "movie_history.csv"),
    index=False
)
movie_interactions.to_csv(
    os.path.join(folder_path, "movie_interactions.csv"),
    index=False
)

# Save train/test split
train_interactions.to_csv(
    os.path.join(folder_path, "movie_train_interactions.csv"),
    index=False
)

test_interactions.to_csv(
    os.path.join(folder_path, "movie_test_interactions.csv"),
    index=False
)

# Save embedding index
embedding_index = items[
    ['id', 'source', 'title']
].copy()

embedding_index.insert(
    0,
    'embedding_index',
    range(len(embedding_index))
)

embedding_index.to_csv(
    os.path.join(folder_path, "embedding_index.csv"),
    index=False
)

print("All Phase-1 files saved.")

All Phase-1 files saved.

In [200]:
item_to_idx = {
    item_id: idx
    for idx, item_id in enumerate(items['id'])
}

In [201]:
assert len(item_to_idx) == len(items)

print("Item → embedding mapping created.")

Item → embedding mapping created.

| File                           | Purpose                                                        |
| ------------------------------ | -------------------------------------------------------------- |
| `items.csv`                    | Final movie/item catalog                                       |
| `movie_history.csv`            | Processed raw watch history, including engagement features     |
| `movie_interactions.csv`       | Aggregated unique `user_id + item_id` interactions             |
| `movie_train_interactions.csv` | Temporal training interactions                                 |
| `movie_test_interactions.csv`  | Temporal held-out interactions                                 |
| `embedding_index.csv`          | Maps embedding row → item ID                                   |
| `item_embeddings.pt`           | SBERT vectors                                                  |