In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# As for the phase-1 our idea is to get the recoomendations on basic (embeddings retreival) no big model 
# clean the datasets (preprocessing and basic embediings retrievals)

In [2]:
df=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\uncleaned_Dataset\netflix_dataset.csv")
df2=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\uncleaned_Dataset\movies.csv")

In [3]:
df.shape

(7787, 12)

In [4]:
df2.shape

(1040, 18)

In [5]:
df.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...

In [6]:
df= df.rename(columns={
    'show_id':'id',
    'listed_in': 'metadata',
    'type': 'domain'
})

In [7]:
df['id'].value_counts()

id
s1       1
s2       1
s3       1
s4       1
s5       1
        ..
s7783    1
s7784    1
s7785    1
s7786    1
s7787    1
Name: count, Length: 7787, dtype: int64

In [ ]:
#As all the id are unique

In [8]:
df['metadata']=df['metadata'].fillna("")+" "+df['description'].fillna("")

In [9]:
# columns which i want to keep
col=['id','title','metadata','domain']
for i in df.columns:
    if i not in col:
        df.drop(i,inplace=True,axis=1)

In [10]:
df.head(1)

   id   domain title                                           metadata
0  s1  TV Show    3%  International TV Shows, TV Dramas, TV Sci-Fi &...

In [11]:
df['domain'].value_counts()

domain
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [12]:
df['metadata'].value_counts()

metadata
Comedies, International Movies, Music & Musicals A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
Action & Adventure, Comedies, Dramas After growing up enduring criticism from his father, a young man finds his world shaken upon learning he was switched at birth with a millionaire’s son.                 2
International Movies, Thrillers As a woman scours Hyderabad for her missing husband, she becomes entangled in a conspiracy that suggests there’s more to the mystery than meets the eye.                      2
Horror Movies, International Movies, Thrillers As a blind librarian, dispirited cricketer and desolate psychiatrist each seek retribution and release, their lives overlap under eerie influences.            2
Comedies, International Movies, Music & Musicals When pretty new neighbor Seema falls for their shy roommate Sid, jealous womanizers Omi and Jai plot to break up the new lovebirds.                          2
                                                                                                                                                                                                             ..
Dramas, International Movies When Lebanon's Civil War deprives Zozo of his family, he's left with grief and little means as he escapes to Sweden in search of his grandparents.                               1
Dramas, International Movies, Music & Musicals A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past.                        1
Documentaries, International Movies, Music & Musicals In this documentary, South African rapper Nasty C hits the stage and streets of Tokyo, introducing himself to the city's sights, sounds and culture.    1
International TV Shows, Reality TV Dessert wizard Adriano Zumbo looks for the next “Willy Wonka” in this tense competition that finds skilled amateurs competing for a $100,000 prize.                        1
Documentaries, Music & Musicals This documentary delves into the mystique behind the blues-rock trio and explores how the enigmatic band created their iconic look and sound.                                 1
Name: count, Length: 7771, dtype: int64

In [13]:
df['title'].value_counts()

title
3%                                         1
07:19                                      1
23:59                                      1
9                                          1
21                                         1
                                          ..
Zozo                                       1
Zubaan                                     1
Zulu Man in Japan                          1
Zumbo's Just Desserts                      1
ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS    1
Name: count, Length: 7787, dtype: int64

In [14]:
df['title'].duplicated().sum()

np.int64(0)

In [ ]:
# no duplicate title names

In [15]:
df2.head(1)

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False

In [16]:
df2.head()

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False
1,movie_0002,Storm Warrior,Stand-up Comedy,Sci-Fi,NaN,2017,37.0,PG,Japanese,USA,3.3,NaN,NaN,NaN,NaN,False,2022-01-28,True
2,movie_0003,Fire Family,Movie,Drama,NaN,2003,142.0,TV-MA,English,USA,8.5,2114120.0,NaN,NaN,NaN,False,2021-05-04,True
3,movie_0004,Our Princess,Documentary,Sci-Fi,NaN,2011,131.0,NC-17,Japanese,USA,5.3,NaN,NaN,NaN,NaN,False,2022-11-26,False
4,movie_0005,Warrior Mission,Documentary,Sport,Mystery,2015,91.0,TV-G,English,USA,3.1,NaN,NaN,NaN,NaN,False,2023-06-15,False

In [17]:
df2['description']=df2['genre_primary'].fillna("")+" "+df2['genre_secondary'].fillna("")

In [18]:
# columns which i want to keep
col=['movie_id','title','content_type','description']
for i in df2.columns:
    if i not in col:
        df2.drop(i,inplace=True,axis=1)

In [19]:
df2= df2.rename(columns={
    'movie_id':'id',
    'description': 'metadata',
    'content_type': 'domain'
})

In [20]:
df2.head()

           id            title           domain          metadata
0  movie_0001    Dragon Legend  Stand-up Comedy  History Thriller
1  movie_0002    Storm Warrior  Stand-up Comedy           Sci-Fi
2  movie_0003      Fire Family            Movie            Drama
3  movie_0004     Our Princess      Documentary           Sci-Fi
4  movie_0005  Warrior Mission      Documentary     Sport Mystery

In [21]:
df.head()

   id   domain  title                                           metadata
0  s1  TV Show     3%  International TV Shows, TV Dramas, TV Sci-Fi &...
1  s2    Movie  07:19  Dramas, International Movies After a devastati...
2  s3    Movie  23:59  Horror Movies, International Movies When an ar...
3  s4    Movie      9  Action & Adventure, Independent Movies, Sci-Fi...
4  s5    Movie     21  Dramas A brilliant group of students become ca...

In [22]:
df.shape

(7787, 4)

In [23]:
df2.shape

(1040, 4)

In [24]:
df2["title"] = df2["title"].str.strip().str.lower()
df2['title'].duplicated().sum()

np.int64(367)

In [25]:
df2.groupby("title").filter(lambda x: len(x) > 1)

              id          title           domain          metadata
1     movie_0002  storm warrior  Stand-up Comedy           Sci-Fi
3     movie_0004   our princess      Documentary           Sci-Fi
7     movie_0008      old house            Movie           Horror
11    movie_0012     bright war            Movie      Crime Sci-Fi
13    movie_0014     little war            Movie          Mystery
...          ...            ...              ...               ...
1035  movie_0140    city empire      Documentary            Sport
1036  movie_0517   storm legend        TV Series              War
1037  movie_0696   house empire   Limited Series        Biography
1038  movie_0056   big princess            Movie  Adventure Comedy
1039  movie_0652      our night            Movie          History

[629 rows x 4 columns]

In [26]:
df2[df2['title']=='old house']

             id      title          domain   metadata
7    movie_0008  old house           Movie    Horror
185  movie_0186  old house       TV Series    Comedy
463  movie_0464  old house  Limited Series     Sport
937  movie_0938  old house           Movie  Crime War

In [ ]:
# as  here old house title has for 4 different domain and metadat so we couldn't convert them directly as all of them are not 
# belong to one type of domain so that makes all of them are unique with respect to content ,as if you give same movie_id for all of them then there will be error
# in the retreival in user watch history as movie_id is primary key we need to match them.

In [27]:
df[df["title"].isin(df2["title"])]

Empty DataFrame
Columns: [id, domain, title, metadata]
Index: []

In [ ]:
df2["title"] = df2["title"].str.strip().str.lower()
df2["domain"] = df2["domain"].fillna('').str.strip()
df2["metadata"] = df2["metadata"].fillna('').str.strip()

In [29]:
df2['title'].duplicated().sum()

np.int64(367)

In [30]:
print(df2.columns)
df.columns

Index(['id', 'title', 'domain', 'metadata'], dtype='str')

Index(['id', 'domain', 'title', 'metadata'], dtype='str')

In [ ]:
## This snippet is valid for if for same movie_title and content it had mistakenly given different movie_id we will handel by 
## same tiltle we will give first movie_id for all of them then there will be error when joining with user_watch histroy as tehre only 
## movie_id will be matching with them 

# # 1. Normalize titles (VERY IMPORTANT)
# df["title"] = df["title"].str.strip().str.lower()
# df2["title"] = df2["title"].str.strip().str.lower()

# # 2. Merge (df2 is PRIMARY)
# merged = pd.merge(df2, df, on="title", how="left", suffixes=("_df2", "_df1"))
# print(merged.head(1))
# merged["metadata"] = (
#     merged["metadata_df2"].fillna('') + " " +
#     merged["metadata_df1"].fillna('')
# ).str.strip()
# merged = merged.drop(columns=["metadata_df2", "metadata_df1"])
# merged["domain"] = (
#     merged["domain_df2"].fillna('') + " " +
#     merged["domain_df1"].fillna('')
# ).str.strip()
# merged = merged.drop(columns=["domain_df2", "domain_df1"])
# merged = merged.drop(columns=["movie_id_df1"])

# merged = merged.rename(columns={"movie_id_df2": "movie_id"})
# # find titles in df that are NOT in df2
# unmatched_df = df[~df["title"].isin(df2["title"])].copy()

# # rename id column to match schema
# unmatched_df = unmatched_df.rename(columns={"id": "id"})

# # add missing columns to match structure
# unmatched_df["movie_id"] = unmatched_df["movie_id"]  # optional placeholder
# merged = merged.reset_index(drop=True)
# unmatched_df = unmatched_df.reset_index(drop=True)
# # unmatched_df = unmatched_df.reindex(columns=merged.columns)

In [32]:
final_df = pd.concat([df, df2], ignore_index=True)

In [33]:
final_df.shape

(8827, 4)

In [34]:
final_df['title'].duplicated().sum()

np.int64(367)

In [35]:
final_df.sample(5)

,id,domain,title,metadata
7688,s7689,Movie,XXx,"Action & Adventure, Sports Movies A notorious ..."
6805,s6806,Movie,The Real Miyagi,"Documentaries, Sports Movies A look at the lif..."
6923,s6924,Movie,The Texas Chainsaw Massacre,"Cult Movies, Horror Movies, Independent Movies..."
2393,s2394,Movie,Ghayal,"Action & Adventure, Dramas, International Movi..."
505,s506,Movie,And Breathe Normally,"Dramas, Independent Movies, International Movi..."

## this dataset contains online courses data

In [36]:
df1=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\uncleaned_Dataset\Online_Courses.csv")

In [37]:
df1.head(1)

,id,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df1['id']=df1['id'].astype(int)

In [39]:
df1[df1['id']==0]

,id,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2819,0,Getting Started with Google Workspace,https://www.udacity.com/course/getting-started...,Learn the necessary skills to be productive wi...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3101,0,Business Ethics: Exploring Big Data and Tax Av...,https://www.futurelearn.com/courses/business-e...,Learn why big data and tax avoidance are some ...,NaN,NaN,NaN,NaN,NaN,NaN,...,Learn why big data and tax avoidance are some ...,4 hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7944,0,Post Graduate Program in Cloud Computing,https://www.simplilearn.com/pgp-cloud-computin...,"The Post Graduate Program in Cloud Computing, ...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,University Program,8583.0,NaN,Cloud Computing

## As you can see there as same id for different items which ,drop and give a unique id

In [40]:
df1 = df1.drop(columns=["id"])      # remove old id
df1["id"] = range(len(df1))         # create new unique id

In [41]:
df1['id'].value_counts()

id
0       1
1       1
2       1
3       1
4       1
       ..
8087    1
8088    1
8089    1
8090    1
8091    1
Name: count, Length: 8092, dtype: int64

In [42]:
df1['id'] = 'n' + df1['id'].astype(str)

In [43]:
df1= df1.rename(columns={
    'Short Intro': 'description',
    'Title': 'title',
    'Skills': 'metadata',
    'Sub-Category': 'domain'
})

In [44]:
df1["title"] = df1["title"].str.strip().str.lower()

In [45]:
df1['metadata']=df1['metadata'].fillna("")+" "+df1['description'].fillna(" ")

In [46]:
# columns which i want to keep
col=['id','title','metadata','domain']
for i in df1.columns:
    if i not in col:
        df1.drop(i,inplace=True,axis=1)

In [47]:
(df1['title'].value_counts()>1).sum()

np.int64(1670)

In [48]:
df1.groupby("title").filter(lambda x: len(x) > 1)

,title,domain,metadata,id
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0
26,business analytics specialization,Data Analysis,"Customer Analytics, Analytics, Business Analyt...",n26
191,market research specialization,Marketing,"Internality, Qualitative Research, quantitativ...",n191
202,machine learning specialization,Machine Learning,"Data Clustering Algorithms, Machine Learning, ...",n202
227,business analytics specialization,Business Essentials,"Machine Learning, Analytics, Data Analysis, po...",n227
...,...,...,...,...
7939,coaching in education: addressing the need for...,NaN,Become better equipped to communicate as a te...,n7939
7940,digital transformation in the classroom,NaN,Adapt your teaching methods to the digital wo...,n7940
7941,education research that matters: ways of resea...,NaN,Discover research methods in education and ho...,n7941
7942,education research that matters: applying rese...,NaN,Discover effective research methods and learn...,n7942
7943,becoming a teacher,NaN,Take your first steps towards teaching with t...,n7943

In [49]:
df1[df1['title']=='becoming a teacher']

,title,domain,metadata,id
4742,becoming a teacher,NaN,Take your first steps towards teaching with t...,n4742
4859,becoming a teacher,NaN,Take your first steps towards teaching with t...,n4859
7943,becoming a teacher,NaN,Take your first steps towards teaching with t...,n7943

In [50]:

df1.shape

(8092, 4)

In [51]:
df1 = df1.drop_duplicates(subset=["title"], keep="first")

In [52]:
df1.head()

,title,domain,metadata,id
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0
1,introduction to data science specialization,Data Analysis,"Data Science, Relational Database Management S...",n1
2,data science fundamentals with python and sql ...,Data Analysis,"Data Science, Github, Python Programming, Jupy...",n2
3,key technologies for business specialization,Business Essentials,"Data Science, Artificial Intelligence (AI), Bu...",n3
4,deep learning specialization,Machine Learning,"Artificial Neural Network, Convolutional Neura...",n4

In [53]:
df=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\uncleaned_Dataset\Courses.csv")

In [54]:
df.head()

,index,Random,course_id,userid_DI,registered,viewed,explored,certified,final_cc_cname_DI,LoE_DI,...,grade,start_time_DI,last_event_DI,nevents,ndays_act,nplay_video,nchapters,nforum_posts,roles,incomplete_flag
0,0,86,HarvardX/CB22x/2013_Spring,MHxPC130442623,1,0,0,0,United States,NaN,...,0,12/19/2012,11/17/2013,NaN,9.0,NaN,NaN,0,NaN,1.0
1,1,7,HarvardX/CS50x/2012,MHxPC130442623,1,1,0,0,United States,NaN,...,0,10/15/2012,NaN,NaN,9.0,NaN,1.0,0,NaN,1.0
2,2,70,HarvardX/CB22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,...,0,2/8/2013,11/17/2013,NaN,16.0,NaN,NaN,0,NaN,1.0
3,3,60,HarvardX/CS50x/2012,MHxPC130275857,1,0,0,0,United States,NaN,...,0,9/17/2012,NaN,NaN,16.0,NaN,NaN,0,NaN,1.0
4,4,3,HarvardX/ER22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,...,0,12/19/2012,NaN,NaN,16.0,NaN,NaN,0,NaN,1.0

In [55]:
# columns which i want to keep
col=['course_id','userid_DI','start_time_DI','ndays_act']
for i in df.columns:
    if i not in col:
        df.drop(i,inplace=True,axis=1)

In [56]:
df["date"] = pd.to_datetime(df["start_time_DI"])
base_date = pd.Timestamp("2014-01-01")
df["month_diff"] = (
    (-df["date"].dt.year + base_date.year) * 12 +
    (-df["date"].dt.month +base_date.month)
)

In [57]:
df.head(5)

,course_id,userid_DI,start_time_DI,ndays_act,date,month_diff
0,HarvardX/CB22x/2013_Spring,MHxPC130442623,12/19/2012,9.0,2012-12-19,13
1,HarvardX/CS50x/2012,MHxPC130442623,10/15/2012,9.0,2012-10-15,15
2,HarvardX/CB22x/2013_Spring,MHxPC130275857,2/8/2013,16.0,2013-02-08,11
3,HarvardX/CS50x/2012,MHxPC130275857,9/17/2012,16.0,2012-09-17,16
4,HarvardX/ER22x/2013_Spring,MHxPC130275857,12/19/2012,16.0,2012-12-19,13

In [58]:
# optional but recommended
df["course_id"] = df["course_id"].str.strip()

# split into parts
split_cols = df["course_id"].str.split("/", expand=True)

# assign required columns
df["institution"] = split_cols[0]
df["course"] = split_cols[1]

In [59]:
df.head(5)

,course_id,userid_DI,start_time_DI,ndays_act,date,month_diff,institution,course
0,HarvardX/CB22x/2013_Spring,MHxPC130442623,12/19/2012,9.0,2012-12-19,13,HarvardX,CB22x
1,HarvardX/CS50x/2012,MHxPC130442623,10/15/2012,9.0,2012-10-15,15,HarvardX,CS50x
2,HarvardX/CB22x/2013_Spring,MHxPC130275857,2/8/2013,16.0,2013-02-08,11,HarvardX,CB22x
3,HarvardX/CS50x/2012,MHxPC130275857,9/17/2012,16.0,2012-09-17,16,HarvardX,CS50x
4,HarvardX/ER22x/2013_Spring,MHxPC130275857,12/19/2012,16.0,2012-12-19,13,HarvardX,ER22x

In [60]:
df['title']=df['institution']+" "+df['course']

In [61]:
df.drop(["course_id","institution"],axis=1,inplace=True)

In [62]:
df= df.rename(columns={
    'userid_DI': 'user_id',
    'course': 'id',
    'ndays_act':'time'
    
})

In [63]:
df['id'].value_counts()

id
CS50x     169621
6.00x     124446
6.002x     63046
ER22x      57406
PH207x     41592
PH278x     39602
8.02x      31048
CB22x      30002
14.73x     27870
7.00x      21009
3.091x     20354
8.MReV      9477
2.01x       5665
Name: count, dtype: int64

# in courses file there are only 7 unique courses

In [64]:
df.shape

(641138, 7)

In [65]:
course_info = {
    "CS50x": {
        "domain": "Computer Science",
        "description": "Introduction to computer science covering algorithms, data structures, C, Python, SQL, and web development."
    },
    "6.00x": {
        "domain": "Programming",
        "description": "Introduction to computer science using Python, focusing on computational thinking and problem solving."
    },
    "6.002x": {
        "domain": "Electrical Engineering",
        "description": "Fundamentals of circuits and electronics including digital logic and system design."
    },
    "ER22x": {
        "domain": "Engineering",
        "description": "Engineering fundamentals with interdisciplinary applications."
    },
    "PH207x": {
        "domain": "Physics",
        "description": "Mechanics and motion including forces, energy, and rotational dynamics."
    },
    "PH278x": {
        "domain": "Physics",
        "description": "Advanced physics concepts with real-world applications."
    },
    "8.02x": {
        "domain": "Physics",
        "description": "Electricity and magnetism including electric fields, circuits, and Maxwell’s equations."
    },
    "CB22x": {
        
        "domain": "Biochemistry",
        "description": "Fundamentals of biochemistry including proteins, DNA, and metabolism."
    },
    "14.73x": {
        
        "domain": "Economics",
        "description": "Data-driven decision making using economic models and statistical analysis."
    },
    "7.00x": {
        
        "domain": "Biology",
        "description": "Introduction to biology including genetics, molecular biology, and cell processes."
    },
    "3.091x": {
        
        "domain": "Chemistry",
        "description": "Introduction to solid-state chemistry and materials science."
    },
    "8.MReV": {
        
        "domain": "Renewable Energy",
        "description": "Physics and mechanics applied to renewable energy systems."
    },
    "2.01x": {
        
        "domain": "Mechanical Engineering",
        "description": "Principles of engineering design, modeling, and system optimization."
    }
}

In [66]:
df.head()

,user_id,start_time_DI,time,date,month_diff,id,title
0,MHxPC130442623,12/19/2012,9.0,2012-12-19,13,CB22x,HarvardX CB22x
1,MHxPC130442623,10/15/2012,9.0,2012-10-15,15,CS50x,HarvardX CS50x
2,MHxPC130275857,2/8/2013,16.0,2013-02-08,11,CB22x,HarvardX CB22x
3,MHxPC130275857,9/17/2012,16.0,2012-09-17,16,CS50x,HarvardX CS50x
4,MHxPC130275857,12/19/2012,16.0,2012-12-19,13,ER22x,HarvardX ER22x

In [67]:
df["domain"] = df["id"].map(lambda x: course_info.get(x, {}).get("domain"))
df["metadata"] = df["id"].map(lambda x: course_info.get(x, {}).get("description"))

In [68]:
df.head()

,user_id,start_time_DI,time,date,month_diff,id,title,domain,metadata
0,MHxPC130442623,12/19/2012,9.0,2012-12-19,13,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...
1,MHxPC130442623,10/15/2012,9.0,2012-10-15,15,CS50x,HarvardX CS50x,Computer Science,Introduction to computer science covering algo...
2,MHxPC130275857,2/8/2013,16.0,2013-02-08,11,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...
3,MHxPC130275857,9/17/2012,16.0,2012-09-17,16,CS50x,HarvardX CS50x,Computer Science,Introduction to computer science covering algo...
4,MHxPC130275857,12/19/2012,16.0,2012-12-19,13,ER22x,HarvardX ER22x,Engineering,Engineering fundamentals with interdisciplinar...

In [69]:
df.drop(["start_time_DI","date"],axis=1,inplace=True)

In [ ]:
import os
# Define the folder path
folder_path = r"C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset"
os.makedirs(folder_path, exist_ok=True)
file_path = os.path.join(folder_path, "course_watch_history.csv")
# Save DataFrame
df.to_csv(file_path, index=False)
print("File saved at:", file_path)

File saved at: C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset\course_watch_history.csv

In [71]:
df.drop(["user_id","time","month_diff"],axis=1,inplace=True)

In [72]:
df.head()

,id,title,domain,metadata
0,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...
1,CS50x,HarvardX CS50x,Computer Science,Introduction to computer science covering algo...
2,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...
3,CS50x,HarvardX CS50x,Computer Science,Introduction to computer science covering algo...
4,ER22x,HarvardX ER22x,Engineering,Engineering fundamentals with interdisciplinar...

In [73]:
df1= pd.concat([df1, df], axis=0, ignore_index=True)
df1= pd.concat([df1, final_df], axis=0, ignore_index=True)

In [74]:
df1.shape

(654868, 4)

In [75]:
df1.duplicated().sum()

np.int64(641165)

In [76]:
df1.drop_duplicates(inplace=True)

In [77]:
df1.isnull().sum()

title          0
domain      2338
metadata       0
id             0
dtype: int64

In [78]:
(df1['title'].value_counts()>1).sum()

np.int64(244)

In [79]:
df1.shape

(13703, 4)

In [80]:
df1['title'].value_counts()

title
a quest            6
a adventure        6
mystery mystery    5
story warrior      5
old house          4
                  ..
last queen         1
the love           1
old phoenix        1
big day            1
ice war            1
Name: count, Length: 13376, dtype: int64

In [81]:
df1[df1['title']=='The Tudors']

,title,domain,metadata,id
652991,The Tudors,TV Show,TV Dramas All the splendor and scandal of Engl...,s6951

In [82]:
df1.shape

(13703, 4)

In [83]:
new_df=df1
del df1

In [84]:
!pip install langid

Requirement already satisfied: langid in c:\nihal\python\venv\lib\site-packages (1.1.6)
Requirement already satisfied: numpy in c:\nihal\python\venv\lib\site-packages (from langid) (2.4.2)

WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)

In [85]:
!pip install deep_translator

Requirement already satisfied: deep_translator in c:\nihal\python\venv\lib\site-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\nihal\python\venv\lib\site-packages (from deep_translator) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\nihal\python\venv\lib\site-packages (from deep_translator) (2.32.4)
Requirement already satisfied: soupsieve>=1.6.1 in c:\nihal\python\venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\nihal\python\venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (4.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\nihal\python\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\nihal\python\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\nihal\python\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\nihal\python\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2025.8.3)

WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\nihal\python\venv\Lib\site-packages)

In [86]:
## As by seeing data in datset we can observe data is from other than english so we should refine into english

import langid
from deep_translator import GoogleTranslator

def convert_to_english(text):
    try:
        lang, _ = langid.classify(text)
        if lang != 'en':
            return GoogleTranslator(source=lang, target='en').translate(text)
        return text
    except:
        return text

new_df['title'] =new_df['title'].apply(convert_to_english)

In [87]:
new_df['domain'] =new_df['domain'].apply(convert_to_english)

In [88]:
new_df['metadata'] =new_df['metadata'].apply(convert_to_english)

## As perform basic preprocessing such as 
Removing i)HTML tags
ii)URLS
iii)Punctutations
iv) stopwords
v) making some of the complex english word convertion into full form.

In [89]:
import re
#by regular expressions
def remove_html_tags(txt):
    pat=re.compile('<.*?>')
    return pat.sub(r'',txt)
def remove_urls(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)
import string,time
ex=string.punctuation
def remove_punc(text):
    for char in ex:
        text=text.replace(char,'')
    return text

In [90]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
STOP_WORDS = stopwords.words("english")
nltk.download('wordnet')
# wee have to do preprocessing
from nltk.stem import WordNetLemmatizer

def preprocess(q):

    q = str(q).lower().strip()

    # Replace certain special characters with their string equivalents
    q = q.replace('"', '')
    q = q.replace('IV', '4')
    q = q.replace('V', '5')
    q = q.replace('VI', '6')

    con= {
    "ain't": "am not",
    "aren't": "are not",
    "can't": "can not",
    "can't've": "can not have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he will have",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "i'd": "i would",
    "i'd've": "i would have",
    "i'll": "i will",
    "i'll've": "i will have",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have"
    }

    q_de = []

    for word in q.split():
        if word in con:
            word = con[word]

        q_de.append(word)

    q = ' '.join(q_de)
    q = q.replace("'ve", " have")
    q = q.replace("n't", " not")
    q = q.replace("'re", " are")
    q = q.replace("'ll", " will")

    # Removing HTML tags
    q = remove_html_tags(q)

    # Remove punctuations
    q = remove_punc(q)
    #remove urls
    q = remove_urls(q)
    # lemmatization
    wordnet_lemmatizer = WordNetLemmatizer()
    q_le=[]
    for word in q.split():
        word = wordnet_lemmatizer.lemmatize(word)

        q_le.append(word)

    q = ' '.join(q_le)
    return q

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nihal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nihal\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [91]:
new_df.head(1)

,title,domain,metadata,id
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0

In [93]:
new_df.head()

,title,domain,metadata,id
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0
1,introduction to data science specialization,Data Analysis,"Data Science, Relational Database Management S...",n1
2,data science fundamentals with python and sql ...,Data Analysis,"Data Science, Github, Python Programming, Jupy...",n2
3,key technologies for business specialization,Business Essentials,"Data Science, Artificial Intelligence (AI), Bu...",n3
4,deep learning specialization,Machine Learning,"Artificial Neural Network, Convolutional Neura...",n4

In [ ]:
new_df['metadata'].apply(preprocess)
new_df['domain'].apply(preprocess)
new_df['title'].apply(preprocess)

0         decision tree artificial neural network logist...
1         data science relational database management sy...
2         data science github python programming jupyter...
3         data science artificial intelligence ai busine...
4         artificial neural network convolutional neural...
                                ...
654823                                                scifi
654824                                    history biography
654825                                              fantasy
654826                                                crime
654827                                                sport
Name: metadata, Length: 13703, dtype: str

In [95]:
new_df.head()

,title,domain,metadata,id
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0
1,introduction to data science specialization,Data Analysis,"Data Science, Relational Database Management S...",n1
2,data science fundamentals with python and sql ...,Data Analysis,"Data Science, Github, Python Programming, Jupy...",n2
3,key technologies for business specialization,Business Essentials,"Data Science, Artificial Intelligence (AI), Bu...",n3
4,deep learning specialization,Machine Learning,"Artificial Neural Network, Convolutional Neura...",n4

In [96]:
new_df.duplicated().sum()

np.int64(0)

In [97]:
new_df.drop_duplicates(inplace=True)

In [98]:
new_df.isnull().sum()

title          0
domain      2338
metadata       0
id             0
dtype: int64

In [99]:
len(new_df)

13703

In [100]:
new_df['combined'] = (
    new_df['metadata'].fillna('') + " " +
    new_df['domain'].fillna('') + " " +
    new_df['title'].fillna('')
)

In [101]:
new_df.head()

,title,domain,metadata,id,combined
0,machine learning specialization,Machine Learning,"Decision Trees, Artificial Neural Network, Log...",n0,"Decision Trees, Artificial Neural Network, Log..."
1,introduction to data science specialization,Data Analysis,"Data Science, Relational Database Management S...",n1,"Data Science, Relational Database Management S..."
2,data science fundamentals with python and sql ...,Data Analysis,"Data Science, Github, Python Programming, Jupy...",n2,"Data Science, Github, Python Programming, Jupy..."
3,key technologies for business specialization,Business Essentials,"Data Science, Artificial Intelligence (AI), Bu...",n3,"Data Science, Artificial Intelligence (AI), Bu..."
4,deep learning specialization,Machine Learning,"Artificial Neural Network, Convolutional Neura...",n4,"Artificial Neural Network, Convolutional Neura..."

In [102]:
new_df['combined'] = new_df['combined'].astype(str)
new_df['combined'] = new_df['combined'].fillna("")
corpus = new_df['combined'].fillna("").astype(str).tolist()

In [103]:
# by Sbert--> Do embeddings

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
# corpus=new_df['combined'].tolist()
arr=model.encode(corpus,convert_to_tensor=True,normalize_embeddings=True)

c:\nihal\python\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 899.14it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [104]:
# test
query1= "Blood & water"
query2="deep learning"
query3="romantic movie"
query4="crime thriller"
query5="guitar music"
query6="history of kings"
query7="world war history military strategy"
query_embedding = model.encode(query1, convert_to_tensor=True)

In [105]:
from sentence_transformers.util import cos_sim

scores = cos_sim(query_embedding,arr)[0]

top_k = 5
top_results = scores.topk(k=top_k)

In [106]:
results = []
for score, idx in zip(top_results.values, top_results.indices):
    row_data = {
        'title': new_df['title'].iloc[idx.item()],
        'domain': new_df['domain'].iloc[idx.item()],
        'metadata': new_df['metadata'].iloc[idx.item()],
        'score': score.item()
    }
    results.append(row_data)
fin = pd.DataFrame(results)

In [107]:
print(fin)

                             title   domain  \
0                    Blood & Water  TV Show
1  human blood and blood functions      NaN
2                Lady in the Water    Movie
3              The Future of Water  TV Show
4                           Oceans    Movie

                                            metadata     score
0  International TV Shows, TV Dramas, TV Mysterie...  0.476042
1   Develop your knowledge of blood, its componen...  0.428358
2  Sci-Fi & Fantasy, Thrillers When an apartment ...  0.377679
3  Docuseries, International TV Shows, Science & ...  0.374072
4  Documentaries, International Movies This docum...  0.366447

In [108]:
new_df.shape

(13703, 5)

In [109]:
new_df['id'].value_counts()

id
n0            1
n1            1
n2            1
n3            1
n4            1
             ..
movie_0996    1
movie_0997    1
movie_0998    1
movie_0999    1
movie_1000    1
Name: count, Length: 13703, dtype: int64

In [110]:
import os

# Define the folder path
folder_path = r"C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset"

# Create folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Define full file path
file_path = os.path.join(folder_path, "movies_courses.csv")

# Save DataFrame
new_df.to_csv(file_path, index=False)

print("File saved at:", file_path)

File saved at: C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset\movies_courses.csv

In [ ]:
df1=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset\course_watch_history.csv") # it is watch history of courses 
df=pd.read_csv(r"C:\nihal\python\NLP\Reccomender_system\uncleaned_Dataset\watch_history.csv") # it watch history of movies users

In [145]:
df1.head(1)

,user_id,time,month_diff,id,title,domain,metadata
0,MHxPC130442623,9.0,13,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...

In [146]:
df1.rename(columns={
    'id':'movie_id'
},inplace=True)

In [147]:
df1.head(1)

,user_id,time,month_diff,movie_id,title,domain,metadata
0,MHxPC130442623,9.0,13,CB22x,HarvardX CB22x,Biochemistry,Fundamentals of biochemistry including protein...

In [148]:
df1['combined'] = (
    df1['metadata'].fillna('') + " " +
    df1['domain'].fillna('') + " " +
    df1['title'].fillna('')
)

In [149]:
df.head(1)

,session_id,user_id,movie_id,watch_date,device_type,watch_duration_minutes,progress_percentage,action,quality,location_country,is_download,user_rating
0,session_000001,user_07271,movie_0511,2025-11-13,Tablet,63.9,34.6,completed,HD,USA,False,NaN

In [150]:
# columns which i want to keep
col=['user_id','movie_id','watch_date','watch_duration_minutes']
for i in df.columns:
    if i not in col:
        df.drop(i,inplace=True,axis=1)

In [151]:
df.rename(columns={"watch_duration_minutes": "time",'watch_date':'date'}, inplace=True)

In [152]:
df["date"] = pd.to_datetime(df["date"])
base_date = pd.Timestamp("2026-01-01")
df["month_diff"] = (
    (-df["date"].dt.year + base_date.year) * 12 +
    (-df["date"].dt.month +base_date.month)
)

In [153]:
df.head()

      user_id    movie_id       date   time  month_diff
0  user_07271  movie_0511 2025-11-13   63.9           2
1  user_00861  movie_0588 2025-02-26  120.1          11
2  user_05391  movie_0694 2024-12-15  572.1          13
3  user_05192  movie_0234 2024-09-30  395.3          16
4  user_05735  movie_0390 2024-08-04   14.6          17

In [154]:
df.shape

(105000, 5)

In [155]:
df.drop(['date'],axis=1,inplace=True)

In [156]:
df['user_id'].value_counts()

user_id
user_06554    26
user_02416    25
user_02512    24
user_02666    24
user_06589    23
              ..
user_03799     2
user_01867     2
user_06905     2
user_09799     2
user_02894     2
Name: count, Length: 10000, dtype: int64

In [157]:
df.drop_duplicates(inplace=True)

In [158]:
movies = {
    row["id"]: {
        "title": row["title"],
        "combined": row['combined'],
        "metadata":row['metadata'],
        "domain":row['domain']
    }
    for _, row in new_df.iterrows()
}
df["title"] = df["movie_id"].map({k: v["title"] for k, v in movies.items()})
df["combined"] = df["movie_id"].map({k: v["combined"] for k, v in movies.items()})
df["metadata"] = df["movie_id"].map({k: v["metadata"] for k, v in movies.items()})
df["domain"] = df["movie_id"].map({k: v["domain"] for k, v in movies.items()})

In [159]:
df1.columns

Index(['user_id', 'time', 'month_diff', 'movie_id', 'title', 'domain',
       'metadata', 'combined'],
      dtype='str')

In [160]:
df.columns

Index(['user_id', 'movie_id', 'time', 'month_diff', 'title', 'combined',
       'metadata', 'domain'],
      dtype='str')

In [163]:
df1= pd.concat([df1, df], axis=0, ignore_index=True)

In [164]:
import os

# Define the folder path
folder_path = r"C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset"

# Create folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Define full file path
file_path = os.path.join(folder_path, "movies_courses_watch_history.csv")

# Save DataFrame
df1.to_csv(file_path, index=False)

print("File saved at:", file_path)

File saved at: C:\nihal\python\NLP\Reccomender_system\Cleaned_dataset\movies_courses_watch_history.csv